/*
 * This file is generated by jOOQ.
 */
package org.yuan.boot.app.db.module.mybatis.jooq.sqlhelper.base.module.dsl;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.yuan.boot.app.db.module.mybatis.jooq.sqlhelper.base.module.dsl.tables.*;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MyAdmin_01 extends SchemaImpl {

    /**
     * The reference instance of <code>my_admin_01</code>
     */
    public static final MyAdmin_01 MY_ADMIN_01 = new MyAdmin_01();
    private static final long serialVersionUID = -311437292;
    /**
     * admin_permission
     */
    public final AdminPermission ADMIN_PERMISSION = AdminPermission.ADMIN_PERMISSION;

    /**
     * admin_role
     */
    public final AdminRole ADMIN_ROLE = AdminRole.ADMIN_ROLE;

    /**
     * admin_role_permission
     */
    public final AdminRolePermission ADMIN_ROLE_PERMISSION = AdminRolePermission.ADMIN_ROLE_PERMISSION;

    /**
     * admin_user
     */
    public final AdminUser ADMIN_USER = AdminUser.ADMIN_USER;

    /**
     * admin_user_role
     */
    public final AdminUserRole ADMIN_USER_ROLE = AdminUserRole.ADMIN_USER_ROLE;

    /**
     * No further instances allowed
     */
    private MyAdmin_01() {
        super("my_admin_01", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                AdminPermission.ADMIN_PERMISSION,
                AdminRole.ADMIN_ROLE,
                AdminRolePermission.ADMIN_ROLE_PERMISSION,
                AdminUser.ADMIN_USER,
                AdminUserRole.ADMIN_USER_ROLE);
    }
}
