server:
  compression:
    enabled: true
  http2:
    enabled: true
  port: 8001

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/learning?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  application:
    name: webmvc-app-project-01
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath*:/mappers/*Mapper.xml

logging:
  level:
    org.minbox.framework.api.boot.plugin.logging: debug

api:
  boot:
    logging:
      admin:
        format-console-log-json: true
      show-console-log: true